#!/usr/bin/env python3
"""
VISTRIKE Model Testing UI - Backend API

Simple Flask wrapper around the inference script for web-based model testing.
"""

import os
import json
import subprocess
import tempfile
import shutil
import atexit
import time
import time as time_module  # Alias for clarity in progress tracking
import re
import threading
from pathlib import Path
from flask import Flask, request, jsonify, send_file, send_from_directory
from flask_cors import CORS
from werkzeug.utils import secure_filename
from werkzeug.exceptions import RequestEntityTooLarge

app = Flask(__name__, static_folder='static', static_url_path='')
CORS(app)

# Configure max file size
app.config['MAX_CONTENT_LENGTH'] = 500 * 1024 * 1024  # 500MB

# Get project root (grandparent of testing-ui/, i.e. VISTRIKE-AI-Official/)
# Path: Vistrike-Main-UI/testing-ui/app.py -> parent.parent.parent = VISTRIKE-AI-Official
PROJECT_ROOT = Path(__file__).parent.parent.parent.resolve()

# Configuration (use absolute paths)
# Save uploads in testing-ui/uploads (cleaned after processing)
UPLOAD_FOLDER = Path(__file__).parent / 'uploads'
RESULTS_FOLDER = PROJECT_ROOT / 'results'  # Store results in project root
ALLOWED_EXTENSIONS = {'mp4', 'avi', 'mov', 'mkv', 'webm'}
MAX_FILE_SIZE = 500 * 1024 * 1024  # 500MB

# Ensure directories exist
UPLOAD_FOLDER.mkdir(parents=True, exist_ok=True)
RESULTS_FOLDER.mkdir(parents=True, exist_ok=True)

print(f"Upload folder: {UPLOAD_FOLDER}")
print(f"Results folder: {RESULTS_FOLDER}")
print(f"Upload folder exists: {UPLOAD_FOLDER.exists()}")
print(f"Upload folder writable: {os.access(str(UPLOAD_FOLDER), os.W_OK)}")

INFERENCE_SCRIPT = PROJECT_ROOT / 'scripts' / '10_inference.py'
INFERENCE_ONNX_SCRIPT = PROJECT_ROOT / 'scripts' / 'inference_onnx.py'


def allowed_file(filename):
    """Check if file extension is allowed."""
    return '.' in filename and filename.rsplit('.', 1)[1].lower() in ALLOWED_EXTENSIONS


@app.route('/')
def index():
    """Serve the main UI page."""
    return send_from_directory('static', 'index.html')


@app.errorhandler(RequestEntityTooLarge)
def handle_file_too_large(e):
    return jsonify({'error': 'File too large', 'details': 'Maximum file size is 500MB'}), 413

@app.route('/api/analyze', methods=['POST'])
def analyze_video():
    """Analyze uploaded video using the inference script."""
    
    print(f"\n{'='*60}")
    print("API: /api/analyze called")
    print(f"{'='*60}")
    
    if 'video' not in request.files:
        print("ERROR: No video file in request")
        return jsonify({'error': 'No video file provided'}), 400
    
    file = request.files['video']
    if file.filename == '':
        print("ERROR: Empty filename")
        return jsonify({'error': 'No file selected'}), 400
    
    # Check file size
    file.seek(0, os.SEEK_END)
    file_size = file.tell()
    file.seek(0)  # Reset file pointer
    
    print(f"Received file: {file.filename}, size: {file_size} bytes ({file_size / 1024 / 1024:.2f} MB)")
    
    if file_size > MAX_FILE_SIZE:
        return jsonify({
            'error': 'File too large',
            'details': f'File size ({file_size / 1024 / 1024:.1f}MB) exceeds maximum ({MAX_FILE_SIZE / 1024 / 1024}MB)'
        }), 413
    
    if not allowed_file(file.filename):
        return jsonify({'error': f'Invalid file type. Allowed: {", ".join(ALLOWED_EXTENSIONS)}'}), 400
    
    # Get parameters
    confidence = float(request.form.get('confidence', 0.5))
    attr_confidence = float(request.form.get('attr_confidence', 0.0))
    device = request.form.get('device', 'cpu')
    save_video_str = request.form.get('save_video', 'true')
    save_video = save_video_str.lower() in ('true', '1', 'yes', 'on')
    # Backend: 'pytorch' (default) uses 10_inference.py; 'onnx' uses inference_onnx.py.
    # ONNX requires .onnx + .meta.json files generated by 12_export_onnx.py.
    backend = request.form.get('backend', 'pytorch').lower()
    print(f"Save video setting: {save_video_str} -> {save_video}")
    print(f"Backend: {backend}")
    
    # Save uploaded file to ui/uploads with unique name
    filename = secure_filename(file.filename)
    video_stem = Path(filename).stem
    timestamp = int(time.time())
    # Use unique filename to avoid conflicts
    unique_filename = f"{video_stem}_{timestamp}{Path(filename).suffix}"
    video_path = UPLOAD_FOLDER / unique_filename
    video_path = video_path.resolve()  # Convert to absolute path
    
    # Ensure upload directory exists
    UPLOAD_FOLDER.mkdir(parents=True, exist_ok=True)
    
    # Save the file
    print(f"Saving file to: {video_path}")
    try:
        file.save(str(video_path))
        saved_size = video_path.stat().st_size if video_path.exists() else 0
        print(f"✓ Video saved successfully")
        print(f"  Path: {video_path}")
        print(f"  Exists: {video_path.exists()}")
        print(f"  Size: {saved_size} bytes ({saved_size / 1024 / 1024:.2f} MB)")
        
        if saved_size != file_size:
            print(f"  WARNING: Size mismatch! Uploaded: {file_size}, Saved: {saved_size}")
    except Exception as e:
        print(f"✗ ERROR saving file: {e}")
        import traceback
        traceback.print_exc()
        return jsonify({
            'error': 'Failed to save uploaded file',
            'details': f'Could not save file: {str(e)}'
        }), 500
    
    # Verify file was saved
    if not video_path.exists():
        return jsonify({
            'error': 'Video file not found after upload',
            'details': f'File was not saved to: {video_path}'
        }), 500
    
    # Create unique output directory (use absolute path)
    output_dir = RESULTS_FOLDER / f"{video_stem}_{timestamp}"
    output_dir = output_dir.resolve()  # Convert to absolute path
    output_dir.mkdir(parents=True, exist_ok=True)
    
    try:
        # Verify video file exists and is readable
        if not video_path.exists():
            return jsonify({
                'error': 'Video file not found',
                'details': f'Uploaded file not found at: {video_path}'
            }), 500
        
        # Verify file is not empty
        if video_path.stat().st_size == 0:
            return jsonify({
                'error': 'Video file is empty',
                'details': f'Uploaded file is empty: {video_path}'
            }), 500
        
        # Select inference script based on backend
        script = INFERENCE_ONNX_SCRIPT if backend == 'onnx' else INFERENCE_SCRIPT
        if not script.exists():
            return jsonify({
                'error': 'Inference script not found',
                'details': f'Script not found at: {script}'
            }), 500
        
        print(f"Running inference ({backend} backend) with:")
        print(f"  Video: {video_path}")
        print(f"  Output: {output_dir}")
        print(f"  Script: {script}")
        
        cmd = [
            'python3', '-u',
            str(script.resolve()),
            '--video', str(video_path),
            '--output', str(output_dir),
            '--confidence', str(confidence),
            '--attr_confidence', str(attr_confidence),
            '--device', device,
            '--save_video', 'true' if save_video else 'false',
            '--output_format', 'json',
        ]
        
        print(f"Command: {' '.join(cmd)}")
        
        # Create progress file (create it immediately with initial state)
        progress_file = output_dir / 'progress.json'
        
        # Get video info first for initial progress
        import cv2
        video_info = {}
        try:
            cap = cv2.VideoCapture(str(video_path))
            if cap.isOpened():
                video_info['total_frames'] = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
                video_info['fps'] = cap.get(cv2.CAP_PROP_FPS)
                video_info['width'] = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                video_info['height'] = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                cap.release()
        except Exception as e:
            print(f"Warning: Could not get video info: {e}")
        
        # Write initial progress state
        initial_progress = {
            'status': 'initializing',
            'current_frame': 0,
            'total_frames': video_info.get('total_frames', 0),
            'message': 'Initializing models and loading video...',
            'device': device.upper(),
            'start_time': time_module.time(),
            'video_resolution': f"{video_info.get('width', 0)}x{video_info.get('height', 0)}" if video_info.get('width') else None,
            'video_fps': float(video_info.get('fps')) if video_info.get('fps') else None,
            'detection_boxes': None,
            'score_range': None,
            'detection_threshold': float(confidence),
            'boxes_above_threshold': None
        }
        try:
            with open(progress_file, 'w') as f:
                json.dump(initial_progress, f)
            print(f"Initial progress file created: {progress_file}")
        except Exception as e:
            print(f"Warning: Could not write initial progress: {e}")
        
        # Return response IMMEDIATELY so frontend can start polling
        # Inference will run in background
        # output_dir is already under RESULTS_FOLDER, so relative path is just the subdirectory name
        output_dir_relative = str(output_dir.relative_to(RESULTS_FOLDER))
        
        print(f"Returning response immediately. Inference will run in background.")
        print(f"Output directory (relative to results): {output_dir_relative}")
        print(f"Output directory (absolute): {output_dir}")
        print(f"Progress file: {progress_file}")
        
        # Start inference in background thread
        print(f"Starting background inference thread...")
        inference_thread = threading.Thread(
            target=run_inference_background,
            args=(cmd, video_path, output_dir, progress_file, confidence, device),
            daemon=True
        )
        inference_thread.start()
        print(f"Background thread started. Thread alive: {inference_thread.is_alive()}")
        
        # Return immediately with output_dir for progress polling
        return jsonify({
            'success': True,
            'output_dir': output_dir_relative,
            'status': 'processing',
            'message': 'Analysis started. Poll /api/progress for updates.'
        })
    
    except Exception as e:
        # Clean up uploaded video on error
        cleanup_uploaded_file(video_path)
        import traceback
        error_details = traceback.format_exc()
        return jsonify({
            'error': 'Analysis failed',
            'details': f"{str(e)}\n\nTraceback:\n{error_details}"
        }), 500


def run_inference_background(cmd, video_path, output_dir, progress_file, confidence, device):
    """Run inference in background thread."""
    try:
        print(f"\n{'='*60}")
        print(f"Background inference started for: {video_path.name}")
        print(f"Command: {' '.join(cmd)}")
        print(f"{'='*60}\n")
        
        # Update progress immediately to show we're starting
        initial_progress = {
            'status': 'processing',
            'current_frame': 0,
            'total_frames': 0,
            'message': 'Starting inference process...',
            'device': device.upper(),
            'start_time': time_module.time(),
            'unified_model': None,
            'action_models': None,
            'detection_boxes': None,
            'score_range': None,
            'detection_threshold': float(confidence),
            'boxes_above_threshold': None
        }
        
        # Get video info if available
        try:
            import cv2
            cap = cv2.VideoCapture(str(video_path))
            if cap.isOpened():
                initial_progress['total_frames'] = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
                initial_progress['video_fps'] = float(cap.get(cv2.CAP_PROP_FPS))
                width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
                height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
                initial_progress['video_resolution'] = f"{width}x{height}"
                cap.release()
        except Exception as e:
            print(f"Warning: Could not get video info: {e}")
        
        try:
            # Ensure directory exists
            progress_file.parent.mkdir(parents=True, exist_ok=True)
            with open(progress_file, 'w') as f:
                json.dump(initial_progress, f)
            print(f"Initial progress written to: {progress_file}")
            print(f"Progress content: {initial_progress}")
            # Verify it was written
            if progress_file.exists():
                print(f"Progress file verified: exists, size={progress_file.stat().st_size} bytes")
            else:
                print(f"ERROR: Progress file was not created!")
        except Exception as e:
            print(f"ERROR: Could not write progress file: {e}")
            import traceback
            traceback.print_exc()
        
        # Run inference with real-time output capture
        # Set PYTHONUNBUFFERED to ensure we get output immediately
        env = os.environ.copy()
        env['PYTHONUNBUFFERED'] = '1'
        
        process = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            universal_newlines=True,
            cwd=str(PROJECT_ROOT),
            env=env
        )
        
        print(f"Inference process started. PID: {process.pid}")
        
        # Patterns for parsing output
        tqdm_pattern = re.compile(r'(\d+)/(\d+)', re.IGNORECASE)  # tqdm format: "123/456"
        frame_pattern = re.compile(r'frame[:\s]+(\d+)', re.IGNORECASE)
        fps_pattern = re.compile(r'(\d+\.?\d*)\s*fps', re.IGNORECASE)
        
        progress_data = {
            'current_frame': 0,
            'total_frames': 0,
            'boxes_detected': 0,
            'avg_confidence': 0.0,
            'fps': 0.0,
            'status': 'processing',
            'message': 'Starting analysis...',
            'start_time': time_module.time(),
            'device': device.upper(),  # Start with provided device
            'unified_model': None,
            'action_models': None,
            'video_resolution': None,
            'video_fps': None,
            'detection_boxes': None,
            'score_range': None,
            'detection_threshold': float(confidence),  # Ensure it's a float
            'boxes_above_threshold': None
        }
        
        # Write initial progress immediately
        try:
            # Ensure directory exists
            progress_file.parent.mkdir(parents=True, exist_ok=True)
            with open(progress_file, 'w') as f:
                json.dump(progress_data, f)
            print(f"Initial progress written to: {progress_file}")
            print(f"Progress content: device={device.upper()}, status={progress_data['status']}")
            # Verify it was written
            if progress_file.exists():
                print(f"Progress file verified: exists, size={progress_file.stat().st_size} bytes")
            else:
                print(f"ERROR: Progress file was not created!")
        except Exception as e:
            print(f"ERROR: Could not write progress file: {e}")
            import traceback
            traceback.print_exc()
        
        # Get video info first (already done above, but update progress_data)
        import cv2
        cap = cv2.VideoCapture(str(video_path))
        if cap.isOpened():
            total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
            fps_video = cap.get(cv2.CAP_PROP_FPS)
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            progress_data['total_frames'] = total_frames
            progress_data['video_fps'] = float(fps_video) if fps_video else None
            progress_data['video_resolution'] = f"{width}x{height}"
            cap.release()
            
            # Write progress with video info
            try:
                with open(progress_file, 'w') as f:
                    json.dump(progress_data, f)
                print(f"Progress updated with video info: {total_frames} frames, {width}x{height}")
            except Exception as e:
                print(f"Warning: Could not write initial progress: {e}")
        
        # Function to monitor analysis.json for real stats
        def monitor_analysis_file():
            analysis_file = output_dir / 'analysis.json'
            last_size = 0
            while process.poll() is None:  # While process is running
                try:
                    if analysis_file.exists():
                        current_size = analysis_file.stat().st_size
                        if current_size > last_size:
                            # Try to read partial JSON (may fail if incomplete)
                            try:
                                with open(analysis_file, 'r') as f:
                                    content = f.read()
                                    # Try to parse - if it fails, it's incomplete
                                    if content.strip().endswith(']') or '"analysis"' in content:
                                        data = json.loads(content)
                                        if 'analysis' in data and len(data['analysis']) > 0:
                                            frames = data['analysis']
                                            progress_data['current_frame'] = len(frames)
                                            
                                            # Calculate stats from actual results
                                            total_boxes = 0
                                            total_conf = 0
                                            conf_count = 0
                                            
                                            for frame_data in frames[-10:]:  # Last 10 frames
                                                persons = frame_data.get('persons', [])
                                                total_boxes += len(persons)
                                                for person in persons:
                                                    conf = person.get('confidence', 0)
                                                    if conf > 0:
                                                        total_conf += conf
                                                        conf_count += 1
                                            
                                            if conf_count > 0:
                                                progress_data['avg_confidence'] = total_conf / conf_count
                                            progress_data['boxes_detected'] = total_boxes // max(len(frames[-10:]), 1)
                                            
                                            # Calculate FPS
                                            if 'start_time' in progress_data:
                                                elapsed = time_module.time() - progress_data['start_time']
                                                if elapsed > 0 and progress_data['current_frame'] > 0:
                                                    progress_data['fps'] = progress_data['current_frame'] / elapsed
                                            
                                            last_size = current_size
                                            
                                            # Write progress
                                            try:
                                                with open(progress_file, 'w') as f:
                                                    json.dump(progress_data, f)
                                            except:
                                                pass
                            except (json.JSONDecodeError, ValueError):
                                # JSON incomplete, that's okay
                                pass
                except:
                    pass
                time.sleep(0.5)  # Check every 500ms
        
        # Start monitoring thread
        monitor_thread = threading.Thread(target=monitor_analysis_file, daemon=True)
        monitor_thread.start()
        
        # Stream output and update progress
        output_lines = []
        unified_loaded = False
        action_models_loaded = []
        
        print("Starting to read process output...")
        line_count = 0
        for line in process.stdout:
            line_count += 1
            output_lines.append(line)
            
            # Print lines containing DEBUG or detection info
            if 'DEBUG' in line or 'Model returned' in line or 'Boxes above' in line or 'threshold' in line.lower():
                print(f"DEBUG line {line_count}: {line.strip()}")
            
            # Parse model loading
            if 'Using device:' in line:
                device_match = re.search(r'Using device:\s*(\w+)', line, re.IGNORECASE)
                if device_match:
                    progress_data['device'] = device_match.group(1).upper()
                    print(f"Device detected: {progress_data['device']}")
                    # Write progress immediately when device is detected
                    try:
                        with open(progress_file, 'w') as f:
                            json.dump(progress_data, f)
                    except:
                        pass
            
            if 'unified model loaded' in line.lower() or 'unified mps model loaded' in line.lower():
                backbone_match = re.search(r'(\w+)\s+backbone', line, re.IGNORECASE)
                if backbone_match:
                    progress_data['unified_model'] = f"Loaded ({backbone_match.group(1)})"
                else:
                    progress_data['unified_model'] = "Loaded"
                unified_loaded = True
                print(f"Unified model loaded: {progress_data['unified_model']}")
                # Write progress immediately
                try:
                    with open(progress_file, 'w') as f:
                        json.dump(progress_data, f)
                except:
                    pass
            
            if 'model loaded' in line.lower() and 'unified' not in line.lower():
                model_match = re.search(r'Loading\s+(\w+)\s+model', line, re.IGNORECASE)
                if model_match:
                    model_name = model_match.group(1)
                    if model_name not in action_models_loaded:
                        action_models_loaded.append(model_name)
                        progress_data['action_models'] = ', '.join(action_models_loaded)
                        print(f"Action model loaded: {model_name}")
                        # Write progress immediately
                        try:
                            with open(progress_file, 'w') as f:
                                json.dump(progress_data, f)
                        except:
                            pass
            
            # Parse video info
            if 'Resolution:' in line:
                res_match = re.search(r'Resolution:\s*(\d+)x(\d+)', line, re.IGNORECASE)
                if res_match:
                    progress_data['video_resolution'] = f"{res_match.group(1)}x{res_match.group(2)}"
            
            if 'FPS:' in line and ('video' in line.lower() or 'Total frames:' in line):
                fps_match = re.search(r'FPS:\s*([\d.]+)', line, re.IGNORECASE)
                if fps_match:
                    progress_data['video_fps'] = float(fps_match.group(1))
            
            # Parse debug detection info - try multiple patterns
            # Pattern 1: "DEBUG: Model returned X boxes, scores range: [min, max], threshold: val"
            if 'DEBUG: Model returned' in line:
                print(f"Found DEBUG line: {line.strip()}")
                
                # Try to match boxes count
                boxes_match = re.search(r'Model returned\s+(\d+)\s+boxes', line, re.IGNORECASE)
                if boxes_match:
                    progress_data['detection_boxes'] = int(boxes_match.group(1))
                    print(f"✓ Parsed detection_boxes: {progress_data['detection_boxes']}")
                else:
                    # Try alternative pattern: "Model returned 0 boxes"
                    boxes_match = re.search(r'Model returned\s+(\d+)\s+boxes', line, re.IGNORECASE)
                    if boxes_match:
                        progress_data['detection_boxes'] = int(boxes_match.group(1))
                        print(f"✓ Parsed detection_boxes (alt): {progress_data['detection_boxes']}")
                
                # Try to match score range: "scores range: [0.1234, 0.5678]"
                score_match = re.search(r'scores range:\s*\[([\d.]+),\s*([\d.]+)\]', line, re.IGNORECASE)
                if score_match:
                    min_score = float(score_match.group(1))
                    max_score = float(score_match.group(2))
                    progress_data['score_range'] = f"[{min_score:.4f}, {max_score:.4f}]"
                    print(f"✓ Parsed score_range: {progress_data['score_range']}")
                
                # Parse threshold from the same line: "threshold: 0.5"
                threshold_match = re.search(r'threshold:\s*([\d.]+)', line, re.IGNORECASE)
                if threshold_match:
                    progress_data['detection_threshold'] = float(threshold_match.group(1))
                    print(f"✓ Parsed detection_threshold: {progress_data['detection_threshold']}")
                
                # Write progress immediately when we get detection stats
                try:
                    with open(progress_file, 'w') as f:
                        json.dump(progress_data, f)
                    print(f"✓ Progress written: boxes={progress_data.get('detection_boxes')}, range={progress_data.get('score_range')}, threshold={progress_data.get('detection_threshold')}")
                except Exception as e:
                    print(f"✗ Error writing progress after detection info: {e}")
            
            # Parse boxes above threshold (can be on separate line)
            # Pattern: "DEBUG: Boxes above threshold: 5"
            if 'Boxes above threshold:' in line:
                print(f"Found boxes above threshold line: {line.strip()}")
                threshold_match = re.search(r'Boxes above threshold:\s*(\d+)', line, re.IGNORECASE)
                if threshold_match:
                    progress_data['boxes_above_threshold'] = int(threshold_match.group(1))
                    print(f"✓ Parsed boxes_above_threshold: {progress_data['boxes_above_threshold']}")
                    # Write progress immediately when we get detection stats
                    try:
                        with open(progress_file, 'w') as f:
                            json.dump(progress_data, f)
                        print(f"✓ Progress written with boxes_above_threshold: {progress_data['boxes_above_threshold']}")
                    except Exception as e:
                        print(f"✗ Error writing progress after boxes above threshold: {e}")
            
            # Parse tqdm progress (format: "123/456" or "Analyzing frames: 45%|████     | 123/456")
            tqdm_match = tqdm_pattern.search(line)
            if tqdm_match:
                try:
                    current = int(tqdm_match.group(1))
                    total = int(tqdm_match.group(2))
                    progress_data['current_frame'] = current
                    if total > 0:
                        progress_data['total_frames'] = total
                    
                    # Parse speed from tqdm (format: "[00:09<07:24, 1.56it/s]")
                    speed_match = re.search(r'([\d.]+)it/s', line)
                    if speed_match:
                        progress_data['fps'] = float(speed_match.group(1))
                except:
                    pass
            
            # Parse frame number (fallback)
            frame_match = frame_pattern.search(line)
            if frame_match and progress_data['current_frame'] == 0:
                try:
                    progress_data['current_frame'] = int(frame_match.group(1))
                except:
                    pass
            
            # Parse FPS from output
            fps_match = fps_pattern.search(line)
            if fps_match and progress_data['fps'] == 0:
                try:
                    progress_data['fps'] = float(fps_match.group(1))
                except:
                    pass
            
            # Update progress message
            line_clean = line.strip()
            if line_clean and len(line_clean) < 100:  # Avoid very long lines
                if 'Analyzing' in line or 'Loading' in line or 'frame' in line.lower() or '%' in line:
                    progress_data['message'] = line_clean
            
            # Write progress file periodically (every 10 lines or on important updates)
            # Also write immediately after parsing detection info
            should_write = (
                line_count % 10 == 0 or 
                unified_loaded or 
                progress_data.get('current_frame', 0) > 0 or
                progress_data.get('detection_boxes') is not None or
                progress_data.get('score_range') is not None
            )
            if should_write:
                try:
                    with open(progress_file, 'w') as f:
                        json.dump(progress_data, f)
                    if line_count % 50 == 0:  # Log every 50 lines
                        print(f"Progress updated: frame {progress_data.get('current_frame', 0)}/{progress_data.get('total_frames', 0)}")
                except Exception as e:
                    print(f"Error writing progress: {e}")
        
        # Wait for process to complete
        result = process.wait()
        
        # Check for annotated video file
        annotated_video = None
        if result == 0:
            # Look for annotated video in output directory
            video_stem = video_path.stem
            possible_videos = [
                output_dir / f"{video_stem}_annotated.mp4",
                output_dir / "annotated.mp4",
            ]
            print(f"Looking for annotated video in: {output_dir}")
            print(f"Video stem: {video_stem}")
            for video_file in possible_videos:
                print(f"  Checking: {video_file} (exists: {video_file.exists()})")
                if video_file.exists():
                    annotated_video = video_file.name
                    print(f"Found annotated video: {annotated_video}")
                    break
            if not annotated_video:
                print(f"WARNING: Annotated video not found. Checked: {[str(v) for v in possible_videos]}")
                # List all files in output directory for debugging
                if output_dir.exists():
                    all_files = list(output_dir.glob('*.mp4'))
                    print(f"All .mp4 files in output dir: {[f.name for f in all_files]}")
        
        # Final progress update
        progress_data['status'] = 'completed' if result == 0 else 'failed'
        progress_data['message'] = 'Analysis completed' if result == 0 else 'Analysis failed'
        if annotated_video:
            progress_data['annotated_video'] = annotated_video
        with open(progress_file, 'w') as f:
            json.dump(progress_data, f)
        
        if result != 0:
            error_msg = '\n'.join(output_lines[-20:])  # Last 20 lines
            print(f"ERROR: Inference failed with return code {result}")
            print(error_msg)
        
        # Clean up uploaded video file
        cleanup_uploaded_file(video_path)
        print(f"Background inference completed for: {video_path.name}")
        
    except Exception as e:
        print(f"ERROR in background inference: {e}")
        import traceback
        traceback.print_exc()
        # Update progress to show error
        try:
            error_progress = {
                'status': 'failed',
                'message': f'Error: {str(e)}',
                'current_frame': 0,
                'total_frames': 0
            }
            with open(progress_file, 'w') as f:
                json.dump(error_progress, f)
        except:
            pass
        cleanup_uploaded_file(video_path)


def cleanup_uploaded_file(video_path):
    """Clean up uploaded video file."""
    try:
        if video_path and video_path.exists():
            video_path.unlink()
            print(f"Cleaned up uploaded video: {video_path}")
    except Exception as e:
        print(f"Warning: Could not delete uploaded video {video_path}: {e}")


@app.route('/api/progress/<path:output_dir>')
def get_progress(output_dir):
    """Get progress updates for analysis."""
    try:
        # output_dir is relative to RESULTS_FOLDER (e.g., "video_123" not "results/video_123")
        progress_file = RESULTS_FOLDER / output_dir / 'progress.json'
        progress_file = progress_file.resolve()
        results_abs = RESULTS_FOLDER.resolve()
        
        # Security check
        if not str(progress_file).startswith(str(results_abs)):
            print(f"Security check failed: {progress_file} not under {results_abs}")
            return jsonify({'error': 'Invalid path'}), 403
        
        print(f"Checking progress file: {progress_file} (exists: {progress_file.exists()})")
        
        if progress_file.exists():
            try:
                with open(progress_file, 'r') as f:
                    progress_data = json.load(f)
                    print(f"Progress data: status={progress_data.get('status')}, device={progress_data.get('device')}")
                    return jsonify(progress_data)
            except Exception as e:
                print(f"Error reading progress file: {e}")
                return jsonify({
                    'status': 'error',
                    'message': f'Error reading progress: {str(e)}'
                }), 500
        
        # Progress file doesn't exist yet - return initial state (but don't return 404, return 200 with initializing status)
        print(f"Progress file not found yet: {progress_file}")
        return jsonify({
            'status': 'initializing',
            'current_frame': 0,
            'total_frames': 0,
            'message': 'Initializing analysis...',
            'device': 'Unknown'
        }), 200  # Changed from 404 to 200 so frontend doesn't treat it as an error
    except Exception as e:
        print(f"Error in get_progress: {e}")
        import traceback
        traceback.print_exc()
        return jsonify({
            'status': 'error',
            'message': f'Error: {str(e)}'
        }), 500

@app.route('/api/results/<path:filename>')
def get_result_file(filename):
    """Serve result files (videos, JSON, etc.)."""
    # Security: only allow files from results folder
    file_path = RESULTS_FOLDER / filename
    # Resolve to absolute path for security check
    file_path = file_path.resolve()
    results_abs = RESULTS_FOLDER.resolve()
    
    if not file_path.exists() or not str(file_path).startswith(str(results_abs)):
        return jsonify({'error': 'File not found'}), 404
    
    return send_file(str(file_path))


@app.route('/api/status')
def status():
    """Health check endpoint."""
    # Check for models
    unified_model = (PROJECT_ROOT / 'models' / 'unified' / 'best.pt').exists()
    unified_mps = (PROJECT_ROOT / 'models' / 'unified_mps' / 'best.pt').exists()
    has_unified = unified_model or unified_mps
    
    return jsonify({
        'status': 'ok',
        'inference_script': str(INFERENCE_SCRIPT.exists()),
        'inference_script_path': str(INFERENCE_SCRIPT),
        'models_dir': str((PROJECT_ROOT / 'models').exists()),
        'has_unified_model': has_unified,
        'unified_model_path': str((PROJECT_ROOT / 'models' / 'unified' / 'best.pt').exists()),
        'unified_mps_path': str((PROJECT_ROOT / 'models' / 'unified_mps' / 'best.pt').exists()),
    })


# Cleanup function to remove upload files on exit
def cleanup_upload_files():
    """Remove upload files from ui/uploads directory."""
    try:
        if UPLOAD_FOLDER.exists():
            deleted_count = 0
            for file in UPLOAD_FOLDER.iterdir():
                try:
                    if file.is_file():
                        # Remove ALL files (they should be cleaned up immediately after processing)
                        file.unlink()
                        deleted_count += 1
                        print(f"Cleaned up upload file: {file.name}")
                except Exception as e:
                    print(f"Error cleaning up {file}: {e}")
            if deleted_count > 0:
                print(f"Cleaned up {deleted_count} upload file(s) from {UPLOAD_FOLDER}")
    except Exception as e:
        print(f"Error in cleanup_upload_files: {e}")

atexit.register(cleanup_upload_files)

# Also clean up on startup - remove ALL files (shouldn't be any left)
cleanup_upload_files()

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 5001))
    print(f"\n{'='*60}")
    print("VISTRIKE Model Testing UI")
    print(f"{'='*60}")
    print(f"Starting server on http://localhost:{port}")
    print(f"Inference script: {INFERENCE_SCRIPT}")
    print(f"Project root: {PROJECT_ROOT}")
    print(f"Upload folder: {UPLOAD_FOLDER}")
    print(f"Results folder: {RESULTS_FOLDER}")
    print(f"{'='*60}\n")
    
    app.run(host='0.0.0.0', port=port, debug=True)
